# Activity Guide (For Students)

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../datasets/dados_streaming.csv')
df.sample(5)

     id_cliente  idade  mensalidade  meses_contrato suporte_tecnico    target
130        1130   45.0        14.32              32             Não      Fiel
360        1360   33.0        12.74              22             Não  Cancelou
207        1207   18.0        18.04              38             Não  Cancelou
388        1388   71.0        19.19              10             Sim      Fiel
151        1151   64.0        17.43               2             Não      Fiel


## Phase 1: Data Audit

### Cleaning: How many customers are missing the age? Fill in these values with the median age.

In [2]:
df['idade'].isnull().sum()

np.int64(15)

In [3]:
df['idade'] = df['idade'].fillna(df['idade'].median())

### Cardinality: How many unique values are there in column suporte_tecnico? And in the target?

In [4]:
print(df['suporte_tecnico'].nunique())
df['suporte_tecnico'].unique()

2

array(['Não', 'Sim'], dtype=object)

In [5]:
print(df['target'].nunique())
df['target'].unique()

2

array(['Fiel', 'Cancelou'], dtype=object)

### Frequency: What percentage of customers have "Canceled" the service? (Tip: use value_counts(normalize=True)).

In [6]:
df['target'].value_counts(normalize=True)

target
Fiel        0.71
Cancelou    0.29
Name: proportion, dtype: float64

## Phase 2: Filters and Logic

### Segmentation: Create a new DataFrame called clientes_premium that contains only those who pay a monthly fee greater than 15.00 and have been in the service for more than 12 months.

In [7]:
clientes_premium = df[(df['mensalidade'] > 15.00) & (df['meses_contrato'] > 12)]
clientes_premium.sample(5)

     id_cliente  idade  mensalidade  meses_contrato suporte_tecnico    target
255        1255   36.0        18.42              47             Não      Fiel
116        1116   61.0        19.41              23             Não      Fiel
355        1355   63.0        15.27              44             Não      Fiel
136        1136   50.0        16.08              21             Sim      Fiel
210        1210   74.0        19.01              37             Sim  Cancelou

### Removal: Does the id_cliente column help predict user behavior? If not, remove it from the DataFrame.

In [8]:
df = df.drop('id_cliente', axis= 1)

## Phase 3: Model Preparation (Encoding)

### Manual Mapping: Turn the target column into numbers: True -> 0, Canceled -> 1.

In [9]:
target_map = {
    'Fiel' : 0,
    'Cancelou': 1
}

df['target'] = df['target'].map(target_map)
df.sample(5)

     idade  mensalidade  meses_contrato suporte_tecnico  target
137   65.0        10.91              14             Não       1
124   52.0        17.82               8             Sim       0
405   34.0        10.42              46             Sim       0
420   70.0        18.21              13             Sim       0
230   41.0        14.05              26             Sim       0

### Binary Mapping: Transform column suporte_tecnico into: No -> 0, Yes -> 1.

In [10]:
df['suporte_tecnico'] = df['suporte_tecnico'].map({'Não':0,'Sim':1})
df.sample(5)

     idade  mensalidade  meses_contrato  suporte_tecnico  target
271   22.0        14.27               1                1       0
487   42.0        13.36              37                0       0
433   48.0        11.54              26                1       0
471   18.0        18.67              42                0       1
314   43.0        10.29              26                0       0

## Phase 4: ML Insights

### Grouping: What is the average meses_contrato for those who canceled vs. those who are loyal?

In [12]:
df.groupby('target')['meses_contrato'].mean()

target
0    24.247887
1    25.434483
Name: meses_contrato, dtype: float64

### Correlation: Is there any strong relationship between the monthly fee and the numerical target?

In [13]:
df.corr()

,idade,mensalidade,meses_contrato,suporte_tecnico,target
idade,1.000000,0.030189,-0.020279,-0.029992,-0.059960
mensalidade,0.030189,1.000000,0.030037,0.019706,-0.080541
meses_contrato,-0.020279,0.030037,1.000000,0.021316,0.039862
suporte_tecnico,-0.029992,0.019706,0.021316,1.000000,0.006693
target,-0.059960,-0.080541,0.039862,0.006693,1.000000

No