# Pandas Tutorial for Machine Learning

## Load Pandas and IRIS dataset

In [1]:
%pwd

'c:\\Users\\mrsou\\ESMAD\\Inteligencia_Artificial\\notebooks'

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('../datasets/Iris.csv')
print(df.head())
df.sample()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
27  28            5.2           3.5            1.5           0.2  Iris-setosa

In [3]:
df.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
24,25,4.8,3.4,1.9,0.2,Iris-setosa
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
7,8,5.0,3.4,1.5,0.2,Iris-setosa

In [4]:
df.Species

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [5]:
df[['PetalLengthCm', 'PetalWidthCm']]

     PetalLengthCm  PetalWidthCm
0              1.4           0.2
1              1.4           0.2
2              1.3           0.2
3              1.5           0.2
4              1.4           0.2
..             ...           ...
145            5.2           2.3
146            5.0           1.9
147            5.2           2.0
148            5.4           2.3
149            5.1           1.8

[150 rows x 2 columns]

In [6]:
np.random.seed(42)
for col in ['PetalLengthCm', 'PetalWidthCm']:
    indices = np.random.choice(df.index, 5, replace=False)
    df.loc[indices, col] = np.nan

print('Dataset altered')

Dataset altered

In [7]:
df.shape

(150, 6)

In [8]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     145.000000    145.000000
mean    75.500000       5.843333      3.054000       3.732414      1.212414
std     43.445368       0.828066      0.433594       1.762136      0.761475
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.500000      0.300000
50%     75.500000       5.800000      3.000000       4.300000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.700000      2.500000

### Step 2: Exploration

Here we learn our categories and class balance

In [9]:
print('Total Species', df['Species'].nunique())

Total Species 3

In [10]:
print('Unique Species', df['Species'].unique())

Unique Species ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [11]:
print('\nSpecies Count')
print(df['Species'].value_counts())

Species Count
Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

### Step 3: Cleaning

Some ML models (like Scikit-Learn) dont accept NaN

In [12]:
print('Null values per collumn', df.isnull().sum())

Null values per collumn Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    5
PetalWidthCm     5
Species          0
dtype: int64

In [13]:
df['PetalLengthCm'] = df['PetalLengthCm'].fillna(df['PetalLengthCm'].mean())
df['PetalWidthCm'] = df['PetalWidthCm'].fillna(df['PetalWidthCm'].mean())

print('\nNot null after treating', df.isnull().sum().sum())

Not null after treating 0

### Step 4: Feature engineering

ML algorithms work using math, so they need numbers. Lets work on the Species collumn

In [14]:
species_map = {
    'Iris-setosa': 0,
    'Iris-versicolor': 1,
    'Iris-virginica': 2
}

df['Species_numeric'] = df['Species'].map(species_map)

print('Trasformation aplied')
print(df[['Species', 'Species_numeric']].sample(10))

Trasformation aplied
             Species  Species_numeric
54   Iris-versicolor                1
71   Iris-versicolor                1
117   Iris-virginica                2
30       Iris-setosa                0
58   Iris-versicolor                1
81   Iris-versicolor                1
10       Iris-setosa                0
64   Iris-versicolor                1
51   Iris-versicolor                1
28       Iris-setosa                0

### Step 5: Correlation Anylasis

What features are more important to predict the species

In [15]:
df_num = df.drop('Species', axis=1)

print('Correlation Matrix')
print(df_num.corr())

Correlation Matrix
                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id               1.000000       0.716676     -0.397729       0.876326
SepalLengthCm    0.716676       1.000000     -0.109369       0.852527
SepalWidthCm    -0.397729      -0.109369      1.000000      -0.396237
PetalLengthCm    0.876326       0.852527     -0.396237       1.000000
PetalWidthCm     0.884988       0.806100     -0.353226       0.930677
Species_numeric  0.942830       0.782561     -0.419446       0.942039

                 PetalWidthCm  Species_numeric
Id                   0.884988         0.942830
SepalLengthCm        0.806100         0.782561
SepalWidthCm        -0.353226        -0.419446
PetalLengthCm        0.930677         0.942039
PetalWidthCm         1.000000         0.936506
Species_numeric      0.936506         1.000000